[build-system]
requires = ["flit_core >=3.4.0,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hydromt_hurrywave"
authors = [
    {name = "Maarten van Ormondt", email = "maarten.vanormondt@deltares-usa.us"},
]
dependencies = [
    "affine",
    "geopandas>1.0",
    "hydromt>=1.3.0,<2.0",
    "numba",
    "numpy",
    "pandas<3.0.0",
    "pydantic",
    "pydantic-settings",
    "pyproj",
    "scipy",
    "shapely",
    "xarray",
    "xugrid>=0.14, <1.0",
    "hydromt",
]
requires-python = ">=3.11"
readme = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Hydrology",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "description"]

[project.urls]
Documentation = "https://deltares.github.io/hydromt_hurrywave/"
Source = "https://github.com/Deltares/hydromt_hurrywave"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
lint = [
    "pre-commit",
    "ruff",
]
doc = [
    "sphinx",
    "sphinx_rtd_theme",
    "nbsphinx",
    "myst-parser",
]
dev = [
    "hydromt_hurrywave[test,lint,doc]",
]

[project.entry-points."hydromt.models"]
hurrywave = "hydromt_hurrywave.hurrywave"

[tool.flit.module]
name = "hydromt_hurrywave"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
ignore = ["E501", "D211", "D213"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D100", "D101", "D102", "D103", "D104"]
